name: Autograding

on: [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Autograding
      uses: education/autograding@v1